### ISSUE TITLE
Integration test is flaky

### ISSUE THREAD

**Issue by samgqroberts** [SylverStudios/WatchWithMe#55]
lol what else is new

Here we see a passing integration test suite in travis:
```
$ npm run integrationTest
> @ integrationTest /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension
> mocha-webpack --webpack-config webpack-config.test.js "src/test/IntegrationTest.js"
 WEBPACK  Compiling...
 WEBPACK  Compiled successfully in 969ms
 MOCHA  Testing...
  integration between server and client
    environment setup
      server location in repository
        ✓ is where it is expected by client testing code
      elixir
        ✓ is installed (93ms)
      mix
        ✓ is installed (68ms)
        ✓ has its dependencies (832ms)
      the server
        ✓ can start and stop (19566ms)
    one client
      ✓ can make a connection (85ms)
      ✓ can disconnect
      ✓ gracefully handles disconnecting while unconnected
      ✓ gracefully handles connecting while already connected
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    two clients
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
      ✓ can detect when each other joins
      with both connected
        ✓ can detect another client's play message
        ✓ can detect another client's pause message
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Uncaught [Error: Could not connect: [object Event]]
    at reportException (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Error: Could not connect: [object Event]
    at onError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/.tmp/mocha-webpack/1561307767645/webpack:/src/client/Client.js:69:1)
    at /home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:908:16
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:907:39)
    at WebSocket.conn.onerror (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/phoenix/priv/static/phoenix.js:823:23)
    at WebSocket.el.addEventListener.event (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at WebSocketImpl._dispatch (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/travis/build/SylverStudios/WatchWithMe/client/chrome-extension/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  12 passing (30s)
 MOCHA  Tests completed successfully
The command "npm run integrationTest" exited with 0.
```

but sometimes at the end there it only says 11 passing, with the `can start and stop server` test timing out after 20s.

**Comment by samgqroberts** [comment]
actually... in this succeeding one...
```
      the server
        ✓ can start and stop (19566ms)
```

the timeout is 20s...

so maybe it's just that the timeout needs to be increased b/c it's very close to the limit.............
